apiVersion: v1
kind: Secret
metadata:
  name: patroni-forgeops
  namespace: pgpool
  labels:
    application: patroni
    cluster-name: patroni-forgeops
type: Opaque
data:
  superuser-password: emFsYW5kbw==          # "zalando" w Base64, zamień na prawdziwe hasło
  replication-password: cmVwLXBhc3M=        # "rep-pass" w Base64, zamień na prawdziwe hasło